# Generated by Django 4.0.4 on 2023-05-29 17:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('lang', models.CharField(default='ru', max_length=7)),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+998', max_length=128, region=None)),
            ],
        ),
    ]
