# Generated by Django 4.0.4 on 2023-05-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['chat_id'], name='sys_user_chat_id_1f622d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fullname'], name='sys_user_fullnam_3f6c1e_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='sys_user',
        ),
    ]
