# Generated by Django 4.0.4 on 2023-06-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.CharField(default='2023-06-09 21:43:31', max_length=1),
            preserve_default=False,
        ),
    ]
