# Generated by Django 4.0.4 on 2023-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_category_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='categories_a',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='categories_b',
            field=models.CharField(default='2023-06-09 23:06:05', max_length=1),
            preserve_default=False,
        ),
    ]
