# Generated by Django 4.0.4 on 2023-06-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_userresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('send_user', models.IntegerField(default=0)),
                ('aktiv_user', models.IntegerField(default=0)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.admin')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamas',
                'db_table': 'reklama',
                'ordering': ['-date_of_created'],
            },
        ),
    ]
